### ISSUE TITLE
Unable to Log In or Post Question using Google Authentication

### ISSUE THREAD

**Issue by tstirrat15** [ros-infrastructure/answers.ros.org#62] opened 2014-01-17 18:15 UTC
When I attempted to ask a question, as a user who has not previously signed up for the site, I clicked the signup/login button at the bottom of the "ask a question" page.

I then selected the option for using my google account, which brought me to the account selection page (I have two google accounts which I use concurrently).

When I clicked on the account that I wanted to use, my browser displayed "waiting for answers.ros.org" and paused for 15-30 seconds. I was then redirected to a page that said "Service Unavailable."

**Comment by briansmith61** [comment] 2014-01-23 06:25
I am facing exactly the similar problem for last 2-3 days. This issue need to be taken care of as early as possible. Otherwise, this excellent community will lose its charm.

**Comment by briansmith61** [comment] 2014-01-23 08:59
I have logged into ROS question and answer board and posted a question which contains 10 lines. But whenever I try to post a detailed question containing image as well, the above error occurs. I have enough karma to post image and link as well. Are the site administrator restricting questions by considering the size or block particular users?

**Comment by tfoote** [comment] 2014-01-23 19:06
@briansmith61 Thanks for finding out that it's related to the size of the message. There aren't any set limits. How big is your content? For large blocks of code and large images it's recommended to link to pastebin or gists and imgur or other hosting soultions. 

@evgenyfadeev Do you know what this problem might be.

**Comment by evgenyfadeev** [comment] 2014-01-26 15:57
I wonder if this is related to issue #60

**Comment by evgenyfadeev** [comment] 2014-01-26 16:16
@tstirrat15 @briansmith61  do you have an issue of simply logging in/registering without posting a question. Just trying to understand whether there is a separate login issue. Thank you.

**Comment by tstirrat15** [comment] 2014-01-27 19:27
I just logged in successfully. It doesn't appear to be a login issue, and it appears that the registration was successful when I was trying to post my question.

**Comment by evgenyfadeev** [comment] 2014-01-27 21:23
Closing because #60 is fixed and I could not reproduce this issue.

**Closed as completed by evgenyfadeev** 2014-01-27 21:23 UTC
