### ISSUE TITLE
Preview and rendered question do not agree

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/answers.ros.org#78] opened 2014-05-22 06:28 UTC
See the initial revision of this question: http://answers.ros.org/question/167946/err-when-using-gscam/

When editing, the preview shows the user's error messages, but in the final post the errors are hidden.

This appears to be related to the use of square brackets, such as: 

```
[FATAL] [1400738699.774908523]: Failed to PAUSE stream, check your gstreamer configuration.
```

**Comment by dirk-thomas** [comment] 2015-01-09 18:37
We can't reproduce this - it seems to be fixed by now. Closing.

If please comment if it is still an issue.

**Closed as completed by dirk-thomas** 2015-01-09 18:37 UTC
