### ISSUE TITLE
Account recovery not sending email

### ISSUE THREAD

**Issue by KyleKotowick** [ros-infrastructure/answers.ros.org#121] opened 2015-05-05 21:15 UTC
I can no longer seem to log into my answers.ros.org account, so I have attempted to "recover" it using the email recovery feature. It confirms that the email address I input was found, and a recovery email has been sent to it. However, after several attempts and several hours of waiting for the email, it never arrives.

Yes, I checked the junk mail folder.

**Comment by tfoote** [comment] 2015-05-06 23:32
I've heard a few reports of emails not going out. 
@evgenyfadeev FYI

**Comment by tfoote** [comment] 2015-05-06 23:33
There are also reports of the email address validation emails not arriving.

**Comment by mikeferguson** [comment] 2015-05-06 23:35
I found mine in the spam folder -- not sure how delayed it was -- but certainly >3 hours after request.

**Comment by adolfo-rt** [comment] 2015-05-07 08:12
I've tried many times over the past week, no email, not even spam. I posted a question to the askbot folks, in case the issue is on their end:

http://askbot.org/en/question/13204/unable-to-recover-account/

**Comment by tfoote** [comment] 2015-05-24 08:04
It looks like there's a connectivity issue. @adolfo-rt to confirm [this post](http://askbot.org/en/question/13204/unable-to-recover-account/?answer=13231#post-id-13231) you did eventually recieve your password reset email?

**Comment by paulbovbel** [comment] 2015-05-24 17:39
Related to the google accounts transition #120, I could never recover my account due to the associated email 'not being in the database'.

**Comment by evgenyfadeev** [comment] 2015-05-24 21:46
@paulbovbel, I've merged your newer account to the older one.
If you can't log in, please try recovering by email (email address was copied as well).

**Comment by adolfo-rt** [comment] 2015-05-25 07:15
I answered myself [the question](http://askbot.org/en/question/13204/unable-to-recover-account/?answer=13231#post-id-13231) a couple of days ago. Copying answer here:

> After many attempts over many days, today the account recovery email made it to my inbox. I can now log in to my account again.
> 
> I don't know what has changed. ROS answers is still at Askbot 0.7.53.

Maybe there was manual intervention, or whatever was blocking email sending was fixed, but when it finally did work, the email was sent 'instantaneously'.

**Comment by evgenyfadeev** [comment] 2015-05-25 17:53
Looks like smtp.osuosl.org is rejecting mail from answers.ros.org.
There is no SPF (just checked) record for answers.ros.org - might be because of that.

Error message in /var/log/mail.log: 

May 25 17:27:32 answers postfix/smtp[27473]: C003725A10: to=root@answers.osuosl.org, orig_to=<root>, relay=smtp.osuosl.org[140.211.166.133]:25, delay=449, delays=449/0.05/0.06/0.01, dsn=4.1.8, status=deferred (host smtp.osuosl.org[140.211.166.133] said: 450 4.1.8 root@answers.osuosl.org: Sender address rejected: Domain not found (in reply to RCPT TO command))

**Comment by tfoote** [comment] 2015-05-26 21:34
We're working on this with our hosting to clean up the DNS entries for better spam filter avoidance.

**Comment by tfoote** [comment] 2015-08-28 17:38
We've added spf entries for answers.ros.org it should be able to avoid spam filters better now.

**Closed as completed by tfoote** 2015-08-28 17:38 UTC
