### ISSUE TITLE
Unable to change Avatar image, "service unavailable"

### ISSUE THREAD

**Issue by skohlbr** [ros-infrastructure/answers.ros.org#50] opened 2013-10-07 12:07 UTC
As described here: http://answers.ros.org/question/87351/unable-to-change-avatar-image-service-unavailable/ I´ve been unable to change my avatar, instead receiving the mentioned error message. Any hints for me or fixes for ROS Answers would be appreciated.

**Comment by kleucht** [comment] 2014-01-10 15:08
This error is occurring for me right now.  I joined answers a couple days ago and it will not let me upload an avatar photo.  It gives a very user unfriendly service unavailable screen.  I noticed that no one is assigned to work this bug.  Is it being worked?

**Comment by skohlbr** [comment] 2014-01-10 15:47
I don´t think so (this bug prevents me from uploading a avatar image since about a year). Let´s try paging @tfoote to see who could be bugged about this :)

**Comment by evgenyfadeev** [comment] 2014-01-10 16:53
thanks, I looking at this issue today.

On Fri, Jan 10, 2014 at 12:47 PM, skohlbr notifications@github.com wrote:

> I don´t think so (this bug prevents me from uploading a avatar image since
> about a year). Let´s try paging @tfoote https://github.com/tfoote to
> see who could be bugged about this :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros-infrastructure/answers.ros.org/issues/50#issuecomment-32038102
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by bradknox** [comment] 2014-01-24 23:23
I am currently having this issue as well. @evgenyfadeev, were you able to find the cause?

**Comment by evgenyfadeev** [comment] 2014-01-27 22:12
there were two database tables on different storage engines linked via foreign key

**Closed as completed by evgenyfadeev** 2014-01-27 22:12 UTC
Labels: bug
