### ISSUE TITLE
I can't submit a question

### ISSUE THREAD

**Issue by pdvelez** [ros-infrastructure/answers.ros.org#67] opened 2014-02-08 18:17 UTC
I have been trying to post a question since yesterday and all I get is the "Service unavailable" notice. However, I see that other users have been posting their questions a couple of hours ago.

**Comment by evgenyfadeev** [comment] 2014-02-10 00:46
Hello, could you tell what is your account name?

On Sat, Feb 8, 2014 at 3:17 PM, pdvelez notifications@github.com wrote:

> I have been trying to post a question since yesterday and all I get is the
> "Service unavailable" notice.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ros-infrastructure/answers.ros.org/issues/67
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by pdvelez** [comment] 2014-02-10 01:26
Hi,

It's Pedro_85

Thanks

On Sunday, February 9, 2014 7:46 PM, Evgeny Fadeev notifications@github.com wrote:

Hello, could you tell what is your account name?

On Sat, Feb 8, 2014 at 3:17 PM, pdvelez notifications@github.com wrote:

> I have been trying to post a question since yesterday and all I get is the
> "Service unavailable" notice.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ros-infrastructure/answers.ros.org/issues/67
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by evgenyfadeev** [comment] 2014-02-11 05:41
Hi, sorry I've tried and could not reproduce.

Could you post here text of question that does not work for you?
I will then try.

Thank you.

Evgeny.

On Sun, Feb 9, 2014 at 10:26 PM, pdvelez notifications@github.com wrote:

> Hi,
> 
> It's Pedro_85
> 
> Thanks
> 
> On Sunday, February 9, 2014 7:46 PM, Evgeny Fadeev <
> notifications@github.com> wrote:
> 
> Hello, could you tell what is your account name?
> 
> On Sat, Feb 8, 2014 at 3:17 PM, pdvelez notifications@github.com wrote:
> 
> > I have been trying to post a question since yesterday and all I get is
> > the
> > "Service unavailable" notice.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ros-infrastructure/answers.ros.org/issues/67>
> > 
> > .
> 
> ## 
> 
> Askbot
> Valparaiso, Chile
> 
> ## skype: evgeny-fadeev
> 
> Reply to this email directly or view it on GitHub.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ros-infrastructure/answers.ros.org/issues/67#issuecomment-34594573
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by pdvelez** [comment] 2014-02-11 19:51
Hi, thank you for your help regarding this issue. 

   I was able to find a solution to the question I was going to ask. Unfortunately, the saved draft of my question is gone. I just tried posting a test question and it worked now. I don't know if something in the code I pasted was creating the error. Since my last attempt I changed the code so I don't have it with me anymore. 

Thanks again for your assistance.

Pedro

On Tuesday, February 11, 2014 12:41 AM, Evgeny Fadeev notifications@github.com wrote:

Hi, sorry I've tried and could not reproduce.

Could you post here text of question that does not work for you?
I will then try.

Thank you.

Evgeny.

On Sun, Feb 9, 2014 at 10:26 PM, pdvelez notifications@github.com wrote:

> Hi,
> 
> It's Pedro_85
> 
> Thanks
> 
> On Sunday, February 9, 2014 7:46 PM, Evgeny Fadeev <
> notifications@github.com> wrote:
> 
> Hello, could you tell what is your account name?
> 
> On Sat, Feb 8, 2014 at 3:17 PM, pdvelez notifications@github.com wrote:
> 
> > I have been trying to post a question since yesterday and all I get is
> > the
> > "Service unavailable" notice.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ros-infrastructure/answers.ros.org/issues/67>
> > 
> > .
> 
> ## 
> 
> Askbot
> Valparaiso, Chile
> 
> ## skype: evgeny-fadeev
> 
> Reply to this email directly or view it on GitHub.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ros-infrastructure/answers.ros.org/issues/67#issuecomment-34594573
> .

## 

Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by AzureViolin** [comment] 2014-04-12 13:15
I've met the same problem and I think I found the problem. When use comma "," as the divider of tags, after submit the question I'll get the "Service Unavailable" Error.

**Comment by evgenyfadeev** [comment] 2014-04-12 13:21
This issue was fixed in the repository last week, I will make an update on your site soon.

**Comment by evgenyfadeev** [comment] 2014-04-19 23:38
fixed

**Closed as completed by evgenyfadeev** 2014-04-19 23:38 UTC
