### ISSUE TITLE
Link from comment area often includes </p>

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#85] opened 2014-07-04 23:05 UTC
Positive example; the [comment from amerino](http://answers.ros.org/question/170971/issues-with-cv_bridge-when-using-cameracalibratorpy-in-indigo/?answer=171051#post-id-171051) becomes `https://github.com/ros-perception/image_pipeline/issues/74%3C/p%3E` and simply clicking the link jumps to http://*`</p>`

Negative example; [A comment here](http://answers.ros.org/question/181892/rostest-code-coverage/?answer=182454#post-id-182454) looks shortened `http://git.io/__B2wg` and it works by just clicking.

**Comment by 130s** [comment] 2014-07-09 23:08
Another negative example found [here](http://answers.ros.org/question/185610/how-to-remove-the-p-and-br-from-my-profile-description/?answer=185614#post-id-185614): `https://github.com/ros-infrastructure/answers.ros.org/issues/86` is linked properly. So it's not github link that always causes this issue.

**Comment by NikolausDemmel** [comment] 2014-07-21 21:48
+1, this has been a long standing an anoying problem. In particular beginners who come to the site for help seem to not realize the additional tag in the link and simply assume the link is dead.

**Comment by NikolausDemmel** [comment] 2014-07-21 21:53
Duplicate of: https://github.com/ros-infrastructure/answers.ros.org/issues/52

**Comment by tfoote** [comment] 2014-08-07 18:50
Closeing as this is a duplicate.

**Closed as completed by tfoote** 2014-08-07 18:50 UTC
Labels: duplicate
